clone_folder: c:\projects\libsoil
os: Visual Studio 2015
configuration: Release

skip_tags: true

matrix:
  include:
    - platform: Win32
      configuration: Debug
      foo: "Visual Studio 14 2015"
    - platform: x64
      configuration: Release
      foo: "Visual Studio 14 2015 Win64"
  
before_build:
    - cd c:\projects\libsoil\projects\win\
    - cmake -G "%foo%"
  
build:
    project: c:\projects\libsoil\projects\win\ALL_BUILD.vcxproj

artifacts:
  - path: .\projects\win\Release\soil.dll
    name: theDLL
    type: File

deploy:
  release: libsoil-v$(appveyor_build_version)-$(PLATFORM)
  description: 'Appveyor Build'
  provider: GitHub
  auth_token:
    secure: XSb9h9W4f7bSSB7IQ3m3wngD2WA/hS0mq/aEDynzsVGkETjkjgq8im67ByH7FDX3
  artifact: theDLL
  draft: false
  prerelease: false
  on:
    branch: master
