clone_folder: c:\projects\libsoil
os: Visual Studio 2015
configuration: Release

skip_tags: true

platform:
  - Win32
  - x64
  
before_build:
  - ps: >-
      If ($env:Platform -Match "Win32") {
        cmake -G "Visual Studio 14 2015"
      } Else {
        cmake -G "Visual Studio 14 2015 Win64"
      }
  
build:
    project: c:\projects\libsoil\projects\win\ALL_BUILD.vcxproj

artifacts:
  - path: .\projects\win\Release\soil.dll
    name: theDLL
    type: File

deploy:
  release: libsoil-v$(appveyor_build_version)-$(PLATFORM)
  description: 'Appveyor Build'
  provider: GitHub
  auth_token:
    secure: XSb9h9W4f7bSSB7IQ3m3wngD2WA/hS0mq/aEDynzsVGkETjkjgq8im67ByH7FDX3
  artifact: theDLL
  draft: false
  prerelease: false
  on:
    branch: master
