clone_folder: c:\projects\libsoil
os: Visual Studio 2015
configuration: Release

before_build:
    - cd c:\projects\libsoil\projects\win\
    - cmake -G "Visual Studio 14 2015 Win64"

platform:
  - Win32
  - x64
    
build:
    project: c:\projects\libsoil\projects\win\ALL_BUILD.vcxproj

deploy:
  release: libsoil-v$(appveyor_build_version)-$(PLATFORM)
  description: 'Appveyor Build'
  provider: GitHub
  auth_token:
    secure: XSb9h9W4f7bSSB7IQ3m3wngD2WA/hS0mq/aEDynzsVGkETjkjgq8im67ByH7FDX3
  artifact: /.*\.dll/
  draft: false
  prerelease: false
  on:
    branch: master
